package processor;

import javax.swing.plaf.TableHeaderUI;

// DEBE DE PARSEAR EL JSON QUE DEVUELVE EL JEFAZO DE FELIX EN SU PROCESO DE PYTHON Y CONVERTIRLO A UN
// OBJETO NODE. UNA VEZ SE CONVIERTA SE GUARDARÁ EN EL PROCESSED QUEUE DEL EQUILIBRATOR
// SE HARÁ DE MANERA ASÍNCRONA
public class PythonOutputParser extends Thread {


}
